# Generated by Django 4.1.2 on 2022-11-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=30)),
            ],
        ),
    ]
