# Generated by Django 4.1.2 on 2022-11-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopcion',
            name='fechaNacimiento',
        ),
    ]
